import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc, getDocs, collection, deleteDoc } from 'firebase/firestore';
import fs from 'fs';
import path from 'path';

// Read .env.local manually for seed execution
const envPath = path.resolve(process.cwd(), '.env.local');
const envVars = {};

if (fs.existsSync(envPath)) {
  const envFileContent = fs.readFileSync(envPath, 'utf8');
  envFileContent.split('\n').forEach(line => {
    const [key, ...value] = line.split('=');
    if (key && value) {
      envVars[key.trim()] = value.join('=').trim();
    }
  });
}

const firebaseConfig = {
  apiKey: envVars['NEXT_PUBLIC_FIREBASE_API_KEY'],
  authDomain: envVars['NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'],
  projectId: envVars['NEXT_PUBLIC_FIREBASE_PROJECT_ID'],
  storageBucket: envVars['NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'],
  messagingSenderId: envVars['NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'],
  appId: envVars['NEXT_PUBLIC_FIREBASE_APP_ID'],
};

if (!firebaseConfig.apiKey || firebaseConfig.apiKey.includes('your_api_key')) {
  console.error('❌ Please fill in your real Firebase API keys inside .env.local first!');
  process.exit(1);
}

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const MOCK_PROP_FIRMS = [
  {
    id: 'firm-propr',
    slug: 'propr',
    name: 'Propr',
    logo: 'https://unavatar.io/x/ProprXYZ',
    website: 'https://propr.xyz',
    brandColor: '#52b788',
    tagline: 'Propr.xyz (@ProprXYZ) - Flagship Crypto Prop Trading & Real-Time Transparency.',
    description: 'Propr (propr.xyz) is the premier flagship crypto prop firm built on Hyperliquid, offering 1-Step & 2-Step evaluations with 90% profit splits and instant USDC payouts.',
    rating: 4.9,
    reviewCount: 1540,
    featured: true,
    trending: true,
    badge: 'Flagship 2026',
    profitSplit: 'Up to 90%',
    maxDrawdown: '6% Static',
    dailyDrawdown: '3% Daily',
    profitTarget: '10% 1-Step',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['1-Step', '2-Step'],
    platforms: ['cTrader', 'MT5', 'Match-Trader'],
    payoutFrequency: 'Bi-Weekly / Fast Track USDT',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 75,
    yearEstablished: 2024,
    headquarters: 'Zug, Switzerland',
    trustScore: 99,
    accountTiers: [
      { accountSize: 5000, price: 60, originalPrice: 75, profitTarget: '10%', maxDrawdown: '6%', dailyDrawdown: '3%' },
      { accountSize: 10000, price: 110, originalPrice: 135, profitTarget: '10%', maxDrawdown: '6%', dailyDrawdown: '3%' },
      { accountSize: 25000, price: 275, originalPrice: 320, profitTarget: '10%', maxDrawdown: '6%', dailyDrawdown: '3%' },
      { accountSize: 50000, price: 495, originalPrice: 580, profitTarget: '10%', maxDrawdown: '6%', dailyDrawdown: '3%' },
      { accountSize: 100000, price: 890, originalPrice: 990, profitTarget: '10%', maxDrawdown: '6%', dailyDrawdown: '3%' },
    ],
    verifiedCoupon: {
      id: 'c-propr',
      firmId: 'firm-propr',
      firmName: 'Propr',
      code: 'PROPR20',
      discount: '20% OFF + 90% Split',
      description: 'Exclusive 20% discount on all challenge tiers at propr.xyz.',
      verified: true,
      highlight: true
    }
  },
  {
    id: 'firm-hyrotrader',
    slug: 'hyrotrader',
    name: 'HyroTrader',
    logo: 'https://unavatar.io/x/hyrotrader_com',
    website: 'https://hyrotrader.com',
    brandColor: '#f59e0b',
    tagline: 'Hyrotrader.com (@hyrotrader_com) - Real Exchange Liquidity & 90% Profit Split.',
    description: 'HyroTrader (hyrotrader.com) connects funded crypto traders directly to tier-1 exchange order books like Bybit and Binance with up to 90% profit splits.',
    rating: 4.8,
    reviewCount: 1120,
    featured: true,
    trending: true,
    badge: 'Tier-1 Liquidity',
    profitSplit: 'Up to 90%',
    maxDrawdown: '10% Max',
    dailyDrawdown: '5% Daily',
    profitTarget: '10% Phase 1',
    minCapital: 5000,
    maxCapital: 200000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['2-Step', '1-Step'],
    platforms: ['Bybit', 'MT5', 'cTrader'],
    payoutFrequency: 'Weekly Crypto / USDT',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 110,
    yearEstablished: 2023,
    headquarters: 'Prague, Czech Republic',
    trustScore: 96,
    accountTiers: [
      { accountSize: 5000, price: 59, originalPrice: 75, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 119, originalPrice: 145, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 249, originalPrice: 290, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 379, originalPrice: 440, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 579, originalPrice: 680, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 200000, price: 969, originalPrice: 1150, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-hyrotrader',
      firmId: 'firm-hyrotrader',
      firmName: 'HyroTrader',
      code: 'HYRO10',
      discount: '10% OFF + 90% Split',
      description: '10% off all challenges at hyrotrader.com.',
      verified: true,
      highlight: true
    }
  },
  {
    id: 'firm-solanafunded',
    slug: 'solana-funded',
    name: 'Solana Funded',
    logo: 'https://unavatar.io/x/solanafunded',
    website: 'https://solanafunded.com',
    brandColor: '#a855f7',
    tagline: 'Solanafunded.com (@solanafunded) - High-Leverage Solana Perpetual Prop Firm.',
    description: 'Solana Funded (solanafunded.com) focuses on high-speed Solana ecosystem tokens and crypto perpetuals.',
    rating: 4.8,
    reviewCount: 810,
    featured: true,
    trending: true,
    badge: 'SOL Ecosystem',
    profitSplit: 'Up to 90%',
    maxDrawdown: '10% Max',
    dailyDrawdown: '5% Daily',
    profitTarget: '8% 1-Step',
    minCapital: 2500,
    maxCapital: 100000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['1-Step', '2-Step'],
    platforms: ['cTrader', 'Bybit'],
    payoutFrequency: 'Instant SOL Payouts',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 65,
    yearEstablished: 2024,
    headquarters: 'Miami, USA',
    trustScore: 96,
    accountTiers: [
      { accountSize: 2500, price: 59, originalPrice: 75, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 159, originalPrice: 190, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 318, originalPrice: 380, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 590, originalPrice: 690, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 990, originalPrice: 1190, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-solanafunded',
      firmId: 'firm-solanafunded',
      firmName: 'Solana Funded',
      code: 'SOLANA20',
      discount: '20% OFF + SOL Bonus',
      description: '20% discount on all challenge sizes at solanafunded.com.',
      verified: true,
      highlight: true
    }
  },
  {
    id: 'firm-foxify',
    slug: 'foxify',
    name: 'Foxify Trade',
    logo: 'https://unavatar.io/x/foxifytrade',
    website: 'https://foxify.trade',
    brandColor: '#f97316',
    tagline: 'Foxify.trade (@foxifytrade) - Decentralized P2P & On-Chain Crypto Prop Trading.',
    description: 'Foxify (foxify.trade) brings decentralized P2P trading and on-chain funding challenges.',
    rating: 4.8,
    reviewCount: 890,
    featured: true,
    badge: 'DeFi Prop Leader',
    profitSplit: 'Up to 90%',
    maxDrawdown: '12% Static',
    dailyDrawdown: '5% Daily',
    profitTarget: '10% Single Phase',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:50',
    evaluationSteps: ['1-Step', 'Instant Funding'],
    platforms: ['Bybit', 'TradeLocker'],
    payoutFrequency: 'Instant On-Chain Payouts',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 60,
    yearEstablished: 2023,
    headquarters: 'Arbitrum Ecosystem',
    trustScore: 95,
    accountTiers: [
      { accountSize: 5000, price: 49, originalPrice: 65, profitTarget: '10%', maxDrawdown: '12%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 99, originalPrice: 125, profitTarget: '10%', maxDrawdown: '12%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 229, originalPrice: 270, profitTarget: '10%', maxDrawdown: '12%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 349, originalPrice: 420, profitTarget: '10%', maxDrawdown: '12%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 549, originalPrice: 650, profitTarget: '10%', maxDrawdown: '12%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-foxify',
      firmId: 'firm-foxify',
      firmName: 'Foxify Trade',
      code: 'FOXIFY15',
      discount: '15% OFF + Free Retry',
      description: 'Get 15% discount on 1-Step Evaluation at foxify.trade.',
      verified: true
    }
  },
  {
    id: 'firm-polyquid',
    slug: 'polyquid',
    name: 'Polyquid',
    logo: 'https://unavatar.io/x/Polyquid',
    website: 'https://polyquid.xyz',
    brandColor: '#8b5cf6',
    tagline: 'Polyquid.xyz (@Polyquid) - Decentralized Crypto Perpetual & Liquidity Engine.',
    description: 'Polyquid (polyquid.xyz) provides decentralized liquidity challenges.',
    rating: 4.8,
    reviewCount: 710,
    featured: true,
    badge: 'DeFi Perps',
    profitSplit: 'Up to 90%',
    maxDrawdown: '10% Trailing',
    dailyDrawdown: '5% Daily',
    profitTarget: '8% 1-Step',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['1-Step', 'Instant Funding'],
    platforms: ['Bybit', 'TradeLocker', 'cTrader'],
    payoutFrequency: 'Instant On-Chain USDC',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 70,
    yearEstablished: 2024,
    headquarters: 'Global / On-Chain',
    trustScore: 95,
    accountTiers: [
      { accountSize: 5000, price: 45, originalPrice: 60, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 85, originalPrice: 110, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 195, originalPrice: 240, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 345, originalPrice: 410, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 545, originalPrice: 640, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-polyquid',
      firmId: 'firm-polyquid',
      firmName: 'Polyquid',
      code: 'POLY15',
      discount: '15% OFF + Instant Payout',
      description: '15% off all challenges at polyquid.xyz.',
      verified: true
    }
  },
  {
    id: 'firm-alphagrid',
    slug: 'alphagrid',
    name: 'AlphaGrid',
    logo: 'https://unavatar.io/x/AlphaGridProp',
    website: 'https://alphagrid.fun',
    brandColor: '#06b6d4',
    tagline: 'Alphagrid.fun (@AlphaGridProp) - High-Velocity Solana & Multi-Chain Protocol.',
    description: 'AlphaGrid (alphagrid.fun) is a Solana-native and multi-chain prop trading protocol.',
    rating: 4.8,
    reviewCount: 620,
    featured: true,
    badge: 'Solana Native',
    profitSplit: 'Up to 90%',
    maxDrawdown: '10% Trailing',
    dailyDrawdown: '4% Daily',
    profitTarget: '8% 1-Step',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['1-Step', 'Instant Funding'],
    platforms: ['cTrader', 'Bybit'],
    payoutFrequency: 'Daily SOL / USDC Payouts',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 90,
    yearEstablished: 2024,
    headquarters: 'Solana Ecosystem',
    trustScore: 94,
    accountTiers: [
      { accountSize: 5000, price: 39, originalPrice: 50, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '4%' },
      { accountSize: 10000, price: 79, originalPrice: 100, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '4%' },
      { accountSize: 25000, price: 179, originalPrice: 220, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '4%' },
      { accountSize: 50000, price: 329, originalPrice: 390, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '4%' },
      { accountSize: 100000, price: 529, originalPrice: 620, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '4%' },
    ],
    verifiedCoupon: {
      id: 'c-alphagrid',
      firmId: 'firm-alphagrid',
      firmName: 'AlphaGrid',
      code: 'ALPHA20',
      discount: '20% OFF Challenges',
      description: '20% discount on all challenge accounts at alphagrid.fun.',
      verified: true
    }
  },
  {
    id: 'firm-hyperpnl',
    slug: 'hyperpnl',
    name: 'HyperPNL',
    logo: 'https://unavatar.io/x/HyperPNL',
    website: 'https://hyperpnl.com',
    brandColor: '#10b981',
    tagline: 'Hyperpnl.com (@HyperPNL) - Gamified On-Chain Crypto Prop Challenges.',
    description: 'HyperPNL (hyperpnl.com) combines gamified perpetual trading challenges on Hyperliquid with institutional funding.',
    rating: 4.9,
    reviewCount: 920,
    featured: true,
    badge: '95% Profit Split',
    profitSplit: 'Up to 95%',
    maxDrawdown: '10% Max',
    dailyDrawdown: '5% Daily',
    profitTarget: '10% Single Phase',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['1-Step', 'Instant Funding'],
    platforms: ['Bybit', 'TradeLocker', 'cTrader'],
    payoutFrequency: 'Daily Crypto Payouts',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 95,
    yearEstablished: 2024,
    headquarters: 'Singapore',
    trustScore: 97,
    accountTiers: [
      { accountSize: 5000, price: 49, originalPrice: 65, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 99, originalPrice: 130, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 229, originalPrice: 280, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 399, originalPrice: 480, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 599, originalPrice: 720, profitTarget: '10%', maxDrawdown: '10%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-hyperpnl',
      firmId: 'firm-hyperpnl',
      firmName: 'HyperPNL',
      code: 'PNL15',
      discount: '15% OFF + 95% Split',
      description: 'Exclusive 15% discount + 95% profit split at hyperpnl.com.',
      verified: true,
      highlight: true
    }
  },
  {
    id: 'firm-hypernova',
    slug: 'hypernova',
    name: 'Hypernova',
    logo: 'https://unavatar.io/x/HypernovaX',
    website: 'https://hypernova.xyz',
    brandColor: '#3b82f6',
    tagline: 'Hypernova.xyz (@HypernovaX) - High-Frequency Crypto Perpetual Engine.',
    description: 'Hypernova (hypernova.xyz) delivers ultra-low latency execution on 80+ perpetual pairs.',
    rating: 4.8,
    reviewCount: 750,
    featured: true,
    badge: 'Ultra Low Latency',
    profitSplit: 'Up to 90%',
    maxDrawdown: '10% Trailing',
    dailyDrawdown: '5% Daily',
    profitTarget: '8% Phase 1',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:100',
    evaluationSteps: ['2-Step', '1-Step'],
    platforms: ['cTrader', 'Bybit'],
    payoutFrequency: 'Instant Automated USDT',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 80,
    yearEstablished: 2024,
    headquarters: 'Grand Cayman',
    trustScore: 94,
    accountTiers: [
      { accountSize: 5000, price: 42, originalPrice: 55, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 79, originalPrice: 99, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 189, originalPrice: 230, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 339, originalPrice: 410, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 539, originalPrice: 650, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-hypernova',
      firmId: 'firm-hypernova',
      firmName: 'Hypernova',
      code: 'NOVA20',
      discount: '20% OFF Challenge',
      description: '20% discount on all challenges at hypernova.xyz.',
      verified: true
    }
  },
  {
    id: 'firm-dizso',
    slug: 'dizso',
    name: 'Dizso Funded',
    logo: 'https://unavatar.io/x/dizsofunded',
    website: 'https://dizso.com',
    brandColor: '#ec4899',
    tagline: 'Dizso.com (@dizsofunded) - Next-Gen Crypto & DEX Prop Funding.',
    description: 'Dizso Funded (dizso.com) provides flexible crypto evaluations with instant funding up to $150k.',
    rating: 4.7,
    reviewCount: 480,
    featured: true,
    badge: 'Instant Payouts',
    profitSplit: 'Up to 90%',
    maxDrawdown: '8% Static',
    dailyDrawdown: '4% Daily',
    profitTarget: '7% Single Phase',
    minCapital: 5000,
    maxCapital: 100000,
    cryptoLeverage: '1:50',
    evaluationSteps: ['1-Step', 'Instant Funding'],
    platforms: ['TradeLocker', 'Match-Trader'],
    payoutFrequency: 'On-Demand Crypto',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 55,
    yearEstablished: 2024,
    headquarters: 'Dubai, UAE',
    trustScore: 93,
    accountTiers: [
      { accountSize: 5000, price: 45, originalPrice: 60, profitTarget: '7%', maxDrawdown: '8%', dailyDrawdown: '4%' },
      { accountSize: 10000, price: 85, originalPrice: 110, profitTarget: '7%', maxDrawdown: '8%', dailyDrawdown: '4%' },
      { accountSize: 25000, price: 195, originalPrice: 240, profitTarget: '7%', maxDrawdown: '8%', dailyDrawdown: '4%' },
      { accountSize: 50000, price: 345, originalPrice: 420, profitTarget: '7%', maxDrawdown: '8%', dailyDrawdown: '4%' },
      { accountSize: 100000, price: 545, originalPrice: 650, profitTarget: '7%', maxDrawdown: '8%', dailyDrawdown: '4%' },
    ],
    verifiedCoupon: {
      id: 'c-dizso',
      firmId: 'firm-dizso',
      firmName: 'Dizso Funded',
      code: 'DIZSO15',
      discount: '15% OFF Instant Funding',
      description: 'Get 15% discount at dizso.com.',
      verified: true
    }
  },
  {
    id: 'firm-chainfunded',
    slug: 'chainfunded',
    name: 'ChainFunded',
    logo: '/logos/chainfunded.png',
    website: 'https://chainfunded.io',
    brandColor: '#22c55e',
    tagline: 'Chainfunded.io (@Chainfunded_io) - Multi-Chain Crypto Prop Funding Protocol.',
    description: 'ChainFunded (chainfunded.io) allows crypto traders to scale up to $500,000 with multi-chain payout support in USDT, USDC, and SOL.',
    rating: 4.7,
    reviewCount: 530,
    featured: true,
    badge: 'Multi-Chain Payouts',
    profitSplit: 'Up to 90%',
    maxDrawdown: '10% Maximum',
    dailyDrawdown: '5% Daily',
    profitTarget: '8% Phase 1',
    minCapital: 2500,
    maxCapital: 100000,
    cryptoLeverage: '1:50',
    evaluationSteps: ['2-Step', '1-Step'],
    platforms: ['MT5', 'Match-Trader'],
    payoutFrequency: 'Bi-Weekly Multi-Chain',
    newsTradingAllowed: true,
    weekendHoldingAllowed: true,
    eaAllowed: true,
    noTimeLimit: true,
    cryptoPairsCount: 70,
    yearEstablished: 2023,
    headquarters: 'Panama City, Panama',
    trustScore: 94,
    accountTiers: [
      { accountSize: 2500, price: 50, originalPrice: 60, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 5000, price: 75, originalPrice: 90, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 10000, price: 120, originalPrice: 150, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 25000, price: 250, originalPrice: 300, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 50000, price: 390, originalPrice: 470, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
      { accountSize: 100000, price: 590, originalPrice: 700, profitTarget: '8%', maxDrawdown: '10%', dailyDrawdown: '5%' },
    ],
    verifiedCoupon: {
      id: 'c-chainfunded',
      firmId: 'firm-chainfunded',
      firmName: 'ChainFunded',
      code: 'CHAIN10',
      discount: '10% OFF All Plans',
      description: '10% discount on all challenge tiers at chainfunded.io.',
      verified: true
    }
  }
];

async function seed() {
  console.log('🧹 Clearing old Firestore documents...');
  const snapshot = await getDocs(collection(db, 'firms'));
  for (const docSnap of snapshot.docs) {
    await deleteDoc(doc(db, 'firms', docSnap.id));
    console.log(`🗑️ Removed document: ${docSnap.id}`);
  }

  console.log('🚀 Seeding Firestore database with brand colors...');
  for (const firm of MOCK_PROP_FIRMS) {
    const docRef = doc(db, 'firms', firm.id);
    await setDoc(docRef, firm, { merge: true });
    console.log(`✅ Uploaded firm: ${firm.name} (${firm.slug}) - Brand: ${firm.brandColor}`);
  }
  console.log('🎉 Firestore database seeding complete!');
  process.exit(0);
}

seed().catch(err => {
  console.error('❌ Seeding failed:', err);
  process.exit(1);
});
